import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/flowbite@1.3.4/dist/flowbite.min.css" />
        <script src="https://unpkg.com/flowbite@1.3.4/dist/flowbite.js"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <h1 className='font-bold mb-5 text-3xl'>CREATE ACCOUNT</h1>

        <div className='grid grid-cols-2 gap-x-10 mb-6'>
          <div /**INPUT NAME*/>
            <div className='mb-2'>
              <label htmlFor='email-adress-icon' className="block mb-2 text-sm font-bold text-gray-900 dark:text-gray-300">Name</label>
              <div className="relative mt-1">
                <div className="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                  <svg className="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z"></path><path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z"></path></svg>
                </div>
                <input type="text" id="email-adress-icon" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Enter your name" />
              </div>
            </div>

            <div /**INPUT GENDER*/>
              <label className="block mb-2 text-sm font-bold text-gray-900 dark:text-gray-400">Gender</label>
              <div className='grid grid-cols-3 gap-x-1'>
                <button type="button" className="text-gray-900 bg-white border border-gray-300 hover:bg-gray-900 hover:text-white font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-gray-600 dark:hover:border-gray-700 dark:focus:ring-gray-800  focus:bg-gray-900 focus:text-white dark:border-white dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:bg-gray-700">Male</button>
                <button type="button" className="text-gray-900 bg-white border border-gray-300 hover:bg-gray-900 hover:text-white font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-gray-600 dark:hover:border-gray-700 dark:focus:ring-gray-800  focus:bg-gray-900 focus:text-white dark:border-white dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:bg-gray-700">Female</button>
                <button type="button" className="text-gray-900 bg-white border border-gray-300 hover:bg-gray-900 hover:text-white font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-gray-600 dark:hover:border-gray-700 dark:focus:ring-gray-800  focus:bg-gray-900 focus:text-white dark:border-white dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:bg-gray-700">Others</button>
              </div>
            </div>

            <div /**INPUT CHECKBOX GENDER*/>
              <div className="flex items-center mb-4">
                <input id="checkbox-3" aria-describedby="checkbox-3" type="checkbox" className="w-4 h-4 text-gray-800 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-gray-800 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600" />
                <label htmlFor='checkbox-3' className="ml-3 text-sm font-medium text-gray-900 dark:text-gray-300">Don't show my gender on my profile.</label>
              </div>
            </div>

            <div /**INPUT BIRTHDAY*/>
              <label className="block mb-2 text-sm font-bold text-gray-900 dark:text-gray-400">Birthday</label>
              <div className="relative mb-3">
                <div className="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                  <svg className="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd"></path></svg>
                </div>
                <input datepicker datepicker-buttons type="text" className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Select date: dd/mm/yyyy" />
              </div>
            </div>

            <div /**INPUT RANGE FROM AGE*/>
              <div>
                <label htmlFor="countries" className="block mb-2 text-sm font-bold text-gray-900 dark:text-gray-400">Range from Age (Result from Searching)</label>
                <select id="countries" className="overflow-scroll scroll mb-3 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                  <option>4</option>
                  <option>5</option>
                  <option>6</option>
                  <option>7</option>
                  <option>8</option>
                  <option>9</option>
                  <option>10</option>
                  <option>11</option>
                  <option>12</option>
                  <option>13</option>
                  <option>14</option>
                  <option>15</option>
                  <option>16</option>
                  <option>17</option>
                  <option>18</option>
                  <option>19</option>
                  <option>20</option>
                </select>
              </div>
            </div>

            <div /**INPUT BIO*/>
              <label className="block mb-2 text-sm font-bold text-gray-900 dark:text-gray-400">Biography</label>
              <textarea id="message" rows={5} className="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Write your biography here."></textarea>
            </div>
, 
          </div>

          <div>

            <div /**INPUT UPLOAD IMAGE */>
              <label className="block mb-2 text-sm font-bold text-gray-900 dark:text-gray-400">Profile Photo</label>
              <div className='grid grid-cols-3 gap-x-5 gap-y-5 mb-3'>
                <div className='w-5 h-5'>
                  
                </div>
                <div className='w-5 h-5'>
                  
                </div>
                <div className='w-5 h-5'>
                  
                </div>
                <div className='w-5 h-5'>
                  
                </div>
                <div className='w-5 h-5'>
                  
                </div>
                <div className='w-5 h-5'>
                  
                </div>
              </div>
            </div>

            <div /**INPUT UPLOAD AUDIO FILE*/>
              <label className="block mb-2 text-sm font-bold text-gray-900 dark:text-gray-300" htmlFor="user_avatar">Profile Audio</label>
              <input className="block w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 cursor-pointer dark:text-gray-400 focus:outline-none focus:border-transparent dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" aria-describedby="user_avatar_help" id="user_avatar" type="file" />
              <div className="mb-3 mt-1 text-sm text-gray-500 dark:text-gray-300" id="user_avatar_help">A profile picture is useful to confirm your are logged into your account</div>
            </div>

            <div /**INPUT OPTIONAL */>
              <label className="block text-center mb-2 text-base font-extrabold text-gray-900 dark:text-gray-300" htmlFor="user_avatar">Optional</label>
              <div /**INPUT INTEREST */>
                <label className="block mb-2 text-sm font-bold text-gray-900 dark:text-gray-300" htmlFor="user_avatar">Interest</label>
              </div>
            </div>

          </div>
          
        </div>

        <button type="button" className="self-center text-white bg-gray-700 hover:bg-gray-800 focus:ring-4 focus:ring-gray-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800">Continue</button>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home 
